services:
  aag-weather-reader:
    image: "${IMAGE_NAME:-gcr.io/panoptes-exp/panoptes-aag}:${TAG_NAME:-latest}"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    init: true
    tty: true
    container_name: aag-weather-reader
    privileged: true
    network_mode: host
    restart: on-failure
    command: [ "python /app/scripts/read-aag.py --config-file /data/config.yaml --storage-dir /json_store --store-result" ]
    volumes:
      - /home/panoptes/pocs/weather:/data
      - /home/panoptes/pocs/json_store:/json_store
  aag-weather-server:
    image: "${IMAGE_NAME:-gcr.io/panoptes-exp/panoptes-aag}:${TAG_NAME:-latest}"
    init: true
    tty: true
    container_name: aag-weather-server
    privileged: true
    network_mode: host
    restart: on-failure
    command: [ "uvicorn scripts/serve-aag:app --host 0.0.0.0 --port 6566" ]
    volumes:
      - /home/panoptes/pocs/weather:/data
      - /home/panoptes/pocs/json_store:/json_store